version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    groups:
      test:
        patterns:
        - "*rspec"
        - "govuk_schemas"
        - "rspec-*"
        - "shoulda-*"
        - "simplecov"
        - "webmock"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
